Parameters:
  StageName:
    Type: String
Resources:
  Distribution:
    Properties:
      DistributionConfig:
        CacheBehaviors:
        - PathPattern: "*.wasm"
          LambdaFunctionAssociations:
            -
              EventType: viewer-request
              LambdaFunctionARN: !Sub
                - '{{resolve:ssm:${SSMParameterName}}}'
                - SSMParameterName: !Sub "${StageName}-edgeauth-FunctionVersion"
          AllowedMethods:
          - GET
          - HEAD
          - OPTIONS
          DefaultTTL: 900
          MaxTTL: 900
          MinTTL: 900
          Compress: true
          ResponseHeadersPolicyId: !Ref WasmResponseHeadersPolicy
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # disabled
          OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac # all sans host
          TargetOriginId: myS3Origin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: 'true'
            Headers:
              - '*'
            Cookies:
              Forward: 'all'
        DefaultCacheBehavior:
          LambdaFunctionAssociations:
            -
              EventType: viewer-request
              LambdaFunctionARN: !Sub
                - '{{resolve:ssm:${SSMParameterName}}}'
                - SSMParameterName: !Sub "${StageName}-edgeauth-FunctionVersion:__version__"
